<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_arm">

  <!-- Robot Arm Properties -->
  <xacro:property name="base_height" value="0.1"/>
  <xacro:property name="base_radius" value="0.08"/>
  <xacro:property name="link1_length" value="0.3"/>
  <xacro:property name="link2_length" value="0.25"/>
  <xacro:property name="link3_length" value="0.2"/>
  <xacro:property name="link4_length" value="0.1"/>
  <xacro:property name="link5_length" value="0.08"/>
  <xacro:property name="link6_length" value="0.05"/>
  <xacro:property name="link_radius" value="0.03"/>
  <xacro:property name="joint_radius" value="0.04"/>
  <xacro:property name="joint_length" value="0.06"/>

  <!-- Materials -->
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0"/>
  </material>
  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <!-- Base Link (Fixed to world) -->
  <link name="world"/>

  <joint name="world_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint 1: Base rotation (yaw) -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="100" velocity="1.0"/>
    <dynamics damping="0.5" friction="0.1"/>
  </joint>

  <link name="link1">
    <visual>
      <geometry>
        <cylinder radius="${joint_radius}" length="${joint_length}"/>
      </geometry>
      <origin xyz="0 0 ${joint_length/2}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${joint_radius}" length="${joint_length}"/>
      </geometry>
      <origin xyz="0 0 ${joint_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 ${joint_length/2}" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Joint 2: Shoulder (pitch) -->
  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${joint_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="1.0"/>
    <dynamics damping="0.5" friction="0.1"/>
  </joint>

  <link name="link2">
    <visual>
      <geometry>
        <cylinder radius="${link_radius}" length="${link1_length}"/>
      </geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius}" length="${link1_length}"/>
      </geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.002"/>
    </inertial>
  </link>

  <!-- Joint 3: Elbow (pitch) -->
  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi*0.75}" upper="${pi*0.75}" effort="100" velocity="1.0"/>
    <dynamics damping="0.5" friction="0.1"/>
  </joint>

  <link name="link3">
    <visual>
      <geometry>
        <cylinder radius="${link_radius}" length="${link2_length}"/>
      </geometry>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius}" length="${link2_length}"/>
      </geometry>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="1.5"/>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Joint 4: Wrist 1 (pitch) -->
  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0 ${link2_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi}" upper="${pi}" effort="50" velocity="1.5"/>
    <dynamics damping="0.3" friction="0.1"/>
  </joint>

  <link name="link4">
    <visual>
      <geometry>
        <cylinder radius="${link_radius*0.8}" length="${link3_length}"/>
      </geometry>
      <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius*0.8}" length="${link3_length}"/>
      </geometry>
      <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.8"/>
      <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0"/>
      <inertia ixx="0.003" ixy="0" ixz="0" iyy="0.003" iyz="0" izz="0.0005"/>
    </inertial>
  </link>

  <!-- Joint 5: Wrist 2 (yaw) -->
  <joint name="joint5" type="revolute">
    <parent link="link4"/>
    <child link="link5"/>
    <origin xyz="0 0 ${link3_length}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="30" velocity="2.0"/>
    <dynamics damping="0.2" friction="0.05"/>
  </joint>

  <link name="link5">
    <visual>
      <geometry>
        <cylinder radius="${link_radius*0.6}" length="${link4_length}"/>
      </geometry>
      <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius*0.6}" length="${link4_length}"/>
      </geometry>
      <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.4"/>
      <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.0002"/>
    </inertial>
  </link>

  <!-- Joint 6: Wrist 3 (roll) -->
  <joint name="joint6" type="revolute">
    <parent link="link5"/>
    <child link="link6"/>
    <origin xyz="0 0 ${link4_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi}" upper="${pi}" effort="20" velocity="2.5"/>
    <dynamics damping="0.1" friction="0.05"/>
  </joint>

  <link name="link6">
    <visual>
      <geometry>
        <cylinder radius="${link_radius*0.5}" length="${link5_length}"/>
      </geometry>
      <origin xyz="0 0 ${link5_length/2}" rpy="0 0 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${link_radius*0.5}" length="${link5_length}"/>
      </geometry>
      <origin xyz="0 0 ${link5_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 ${link5_length/2}" rpy="0 0 0"/>
      <inertia ixx="0.0003" ixy="0" ixz="0" iyy="0.0003" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- End Effector (Tool Center Point) -->
  <joint name="ee_joint" type="fixed">
    <parent link="link6"/>
    <child link="ee_link"/>
    <origin xyz="0 0 ${link5_length}" rpy="0 0 0"/>
  </joint>

  <link name="ee_link">
    <visual>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <!-- Include Gazebo-specific elements -->
  <xacro:include filename="$(find robot_description)/urdf/robot_arm.gazebo.xacro"/>

</robot>
